import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Check, ChevronRight, Clock3, FileCheck2, FileText, Fingerprint, Gauge, Globe2, LockKeyhole, MailCheck, PenLine, Scale, ShieldCheck, Sparkles, UploadCloud, Users } from "lucide-react";

const workflows = [
  { icon: BriefcaseBusiness, title: "Sales agreements", copy: "Move proposals, order forms, and contracts from approved to signed without chasing email threads." },
  { icon: Users, title: "People operations", copy: "Send offers, policies, and onboarding documents with a clear record for every employee." },
  { icon: Scale, title: "Legal and compliance", copy: "Standardize templates, control who signs, and keep a complete audit trail with the final document." },
  { icon: Globe2, title: "Client services", copy: "Give every client a polished signing experience on desktop or mobile—no account required." },
];

const steps = [
  { number: "01", icon: UploadCloud, title: "Prepare", copy: "Upload a PDF, assign recipients, and place signature, date, text, and checkbox fields." },
  { number: "02", icon: MailCheck, title: "Send", copy: "Set the signing order and send a secure invitation with a focused path for every recipient." },
  { number: "03", icon: FileCheck2, title: "Track", copy: "See who viewed or signed, then keep the completed agreement and its audit history together." },
];

const footerGroups = [
  { title: "Product", links: [["Features", "#product"], ["How it works", "#how-it-works"], ["Security", "#security"], ["Sign in", "/signin"]] },
  { title: "Solutions", links: [["Sales", "#use-cases"], ["People operations", "#use-cases"], ["Legal", "#use-cases"], ["Client services", "#use-cases"]] },
  { title: "Company", links: [["Get started", "/signup"], ["Contact", "mailto:hello@send.frogmentec.ae"], ["Privacy", "#"], ["Terms", "#"]] },
];

function Mark({ light = false }: { light?: boolean }) {
  return <span className={`grid size-9 place-items-center rounded-[10px] ${light ? "bg-white text-[#102a43]" : "bg-[#102a43] text-white"}`} aria-hidden="true"><svg viewBox="0 0 24 24" className="size-5 fill-none" stroke="currentColor" strokeWidth="2"><path d="M6 3.5h7l5 5V20.5H6z" strokeLinejoin="round" /><path d="M13 3.5v5h5M8.7 15.2l1.8 1.8 4.8-5" strokeLinecap="round" strokeLinejoin="round" /></svg></span>;
}

export default function Home() {
  return <main id="top" className="overflow-hidden bg-[#fbfcfa] text-[#102a43]">
    <header className="relative z-50 border-b border-[#102a43]/10 bg-[#fbfcfa]/95 backdrop-blur-xl">
      <nav className="mx-auto flex h-[72px] max-w-[1240px] items-center justify-between px-5 sm:px-8">
        <Link href="#top" className="flex items-center gap-2.5" aria-label="Signet home"><Mark /><span className="text-xl font-bold tracking-[-0.04em]">signet</span></Link>
        <div className="hidden items-center gap-8 text-sm font-medium text-[#52677a] lg:flex"><Link href="#product" className="transition hover:text-[#102a43]">Product</Link><Link href="#use-cases" className="transition hover:text-[#102a43]">Solutions</Link><Link href="#security" className="transition hover:text-[#102a43]">Security</Link></div>
        <div className="flex items-center gap-2 sm:gap-3"><Link href="/signin" className="px-3 py-2 text-sm font-semibold text-[#334e68] transition hover:text-[#0b6b53]">Sign in</Link><Link href="/signup" className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#0b6b53] px-4 text-sm font-semibold text-white transition hover:bg-[#085641] sm:px-5">Create account <ArrowRight className="size-3.5" /></Link></div>
      </nav>
    </header>

    <section className="relative border-b border-[#102a43]/10">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[520px] bg-[radial-gradient(circle_at_70%_10%,rgba(179,229,214,.5),transparent_42%)]" />
      <div className="relative mx-auto grid max-w-[1240px] items-center gap-14 px-5 py-16 sm:px-8 sm:py-20 lg:min-h-[680px] lg:grid-cols-[0.93fr_1.07fr] lg:gap-14 lg:py-24">
        <div className="max-w-[600px]">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#0b6b53]/20 bg-[#edf8f4] px-3 py-1.5 text-xs font-bold text-[#0b6b53]"><BadgeCheck className="size-3.5" />Secure electronic signatures for growing teams</div>
          <h1 className="text-[3.25rem] font-semibold leading-[0.98] tracking-[-0.06em] text-balance sm:text-[4.5rem] lg:text-[5rem]">Get agreements signed. <span className="text-[#0b6b53]">Keep business moving.</span></h1>
          <p className="mt-7 max-w-[555px] text-lg leading-8 text-[#52677a]">Prepare, send, sign, and track business documents from one secure workspace. Less follow-up for your team, less friction for your clients.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex h-13 items-center justify-center gap-2 rounded-lg bg-[#0b6b53] px-7 text-sm font-bold text-white shadow-[0_16px_35px_-18px_rgba(11,107,83,.7)] transition hover:-translate-y-0.5 hover:bg-[#085641]">Start sending documents <ArrowRight className="size-4" /></Link><Link href="#product" className="inline-flex h-13 items-center justify-center gap-2 rounded-lg border border-[#102a43]/18 bg-white px-7 text-sm font-bold transition hover:border-[#102a43]/35">See the workflow <ChevronRight className="size-4" /></Link></div>
          <div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-xs font-semibold text-[#62788b]"><span className="flex items-center gap-1.5"><Check className="size-3.5 text-[#0b6b53]" />No credit card</span><span className="flex items-center gap-1.5"><Check className="size-3.5 text-[#0b6b53]" />Works on any device</span><span className="flex items-center gap-1.5"><Check className="size-3.5 text-[#0b6b53]" />Audit trail included</span></div>
        </div>
        <div className="relative mx-auto w-full max-w-[620px]">
          <div className="rounded-[24px] border border-[#102a43]/12 bg-[#e9f0ed] p-3 shadow-[0_32px_80px_-38px_rgba(16,42,67,.45)] sm:p-4"><div className="overflow-hidden rounded-[17px] border border-[#102a43]/10 bg-white">
            <div className="flex items-center justify-between border-b border-[#102a43]/10 px-5 py-4"><div className="flex items-center gap-3"><Mark /><div><p className="text-xs font-bold">Consulting agreement</p><p className="mt-0.5 text-[10px] text-[#8293a3]">Acme Studio · 2 recipients</p></div></div><span className="rounded-full bg-[#fff5d9] px-3 py-1 text-[10px] font-bold text-[#8c6200]">Awaiting signature</span></div>
            <div className="grid bg-[#f2f5f3] p-4 sm:grid-cols-[1fr_160px] sm:p-6"><div className="relative min-h-[420px] bg-white px-8 py-9 shadow-[0_8px_28px_-18px_rgba(16,42,67,.3)] sm:px-11">
              <div className="flex items-center justify-between border-b border-[#102a43]/10 pb-6"><div><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-[#0b6b53]">Acme Studio</p><h2 className="mt-2 text-xl font-semibold tracking-[-0.035em]">Consulting Agreement</h2></div><FileText className="size-6 text-[#8293a3]" /></div>
              <p className="mt-7 text-[9px] font-bold uppercase tracking-[0.15em] text-[#8293a3]">Scope of services</p><div className="mt-3 space-y-2"><div className="h-1.5 w-full rounded bg-[#e8eeeb]" /><div className="h-1.5 w-[94%] rounded bg-[#e8eeeb]" /><div className="h-1.5 w-[80%] rounded bg-[#e8eeeb]" /></div>
              <p className="mt-7 text-[9px] font-bold uppercase tracking-[0.15em] text-[#8293a3]">Terms</p><div className="mt-3 space-y-2"><div className="h-1.5 w-full rounded bg-[#e8eeeb]" /><div className="h-1.5 w-[91%] rounded bg-[#e8eeeb]" /><div className="h-1.5 w-[72%] rounded bg-[#e8eeeb]" /></div>
              <div className="absolute bottom-9 left-8 right-8 sm:left-11 sm:right-11"><p className="mb-2 text-[8px] font-bold uppercase tracking-[0.14em] text-[#6f8192]">Client signature</p><div className="flex h-[66px] items-center justify-between rounded-lg border-2 border-[#0b6b53] bg-[#edf8f4] px-5"><span className="text-sm font-semibold text-[#0b6b53]">Click to sign</span><PenLine className="size-5 text-[#0b6b53]" /></div></div>
            </div><aside className="hidden flex-col border-l border-[#102a43]/10 pl-5 sm:flex"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-[#718396]">Recipients</p><div className="mt-5 flex items-center gap-2.5"><span className="grid size-8 place-items-center rounded-full bg-[#d9eee7] text-[9px] font-bold text-[#0b6b53]">AM</span><div><p className="text-[10px] font-bold">Alex Morgan</p><p className="text-[8px] text-[#8293a3]">Needs to sign</p></div></div><div className="mt-4 flex items-center gap-2.5"><span className="grid size-8 place-items-center rounded-full bg-[#e8edf2] text-[9px] font-bold">SK</span><div><p className="text-[10px] font-bold">Sara Khan</p><p className="text-[8px] text-[#8293a3]">Receives a copy</p></div></div><div className="mt-auto rounded-xl bg-[#102a43] p-4 text-white"><div className="flex items-center gap-2 text-[9px] font-bold"><LockKeyhole className="size-3.5" />Secure delivery</div><p className="mt-2 text-[9px] leading-4 text-white/60">Access and signature activity are recorded automatically.</p></div></aside></div>
          </div></div>
          <div className="absolute -bottom-5 -left-3 flex items-center gap-3 rounded-xl border border-[#102a43]/10 bg-white px-4 py-3 shadow-[0_18px_40px_-22px_rgba(16,42,67,.45)] sm:-left-7"><span className="grid size-9 place-items-center rounded-lg bg-[#edf8f4] text-[#0b6b53]"><Clock3 className="size-4" /></span><div><p className="text-[10px] font-bold">Sent 2 minutes ago</p><p className="text-[9px] text-[#8293a3]">Delivery confirmed</p></div></div>
        </div>
      </div>
    </section>

    <section className="border-b border-[#102a43]/10 bg-white"><div className="mx-auto grid max-w-[1160px] grid-cols-2 divide-x divide-[#102a43]/10 px-5 py-8 sm:px-8 lg:grid-cols-4">{[['One workspace', 'Documents, people, and progress'], ['Clear status', 'Know exactly what happens next'], ['Built-in record', 'Every key event captured'], ['Mobile ready', 'Sign from anywhere']].map(([title, copy], index) => <div key={title} className={`px-4 py-4 sm:px-6 ${index > 1 ? 'border-t border-[#102a43]/10 lg:border-t-0' : ''}`}><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-[#6a7d8e]">{copy}</p></div>)}</div></section>

    <section id="use-cases" className="px-5 py-24 sm:px-8 sm:py-28"><div className="mx-auto max-w-[1160px]"><div className="grid gap-8 lg:grid-cols-[0.75fr_1.25fr] lg:gap-20"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#0b6b53]">Built around real work</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">A reliable next step for every agreement.</h2></div><p className="max-w-xl self-end text-base leading-7 text-[#5d7285]">Whether one person sends contracts or an entire team manages approvals, Signet keeps the process consistent, visible, and easy for everyone involved.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-[#102a43]/10 bg-[#102a43]/10 md:grid-cols-2">{workflows.map(({ icon: Icon, title, copy }) => <article key={title} className="bg-white p-7 sm:p-9"><Icon className="size-5 text-[#0b6b53]" /><h3 className="mt-7 text-xl font-bold tracking-[-0.03em]">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-[#617587]">{copy}</p></article>)}</div></div></section>

    <section id="product" className="bg-[#102a43] px-5 py-24 text-white sm:px-8 sm:py-28"><div className="mx-auto max-w-[1160px]"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#8dd7c2]">One connected workflow</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">From document to done—without the handoffs.</h2></div><div id="how-it-works" className="mt-14 grid gap-4 lg:grid-cols-3">{steps.map(({ number, icon: Icon, title, copy }) => <article key={number} className="rounded-2xl border border-white/12 bg-white/[0.055] p-7"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl bg-[#8dd7c2] text-[#102a43]"><Icon className="size-5" /></span><span className="font-mono text-xs text-white/35">{number}</span></div><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{copy}</p></article>)}</div><div className="mt-5 grid gap-4 rounded-2xl border border-white/12 bg-white/[0.055] p-7 md:grid-cols-3 md:p-9"><div className="flex gap-3"><Gauge className="mt-0.5 size-5 shrink-0 text-[#8dd7c2]" /><div><p className="text-sm font-bold">Live status</p><p className="mt-1 text-xs leading-5 text-white/55">See sent, viewed, and completed activity.</p></div></div><div className="flex gap-3"><Sparkles className="mt-0.5 size-5 shrink-0 text-[#8dd7c2]" /><div><p className="text-sm font-bold">Reusable templates</p><p className="mt-1 text-xs leading-5 text-white/55">Turn repeat documents into repeatable processes.</p></div></div><div className="flex gap-3"><Fingerprint className="mt-0.5 size-5 shrink-0 text-[#8dd7c2]" /><div><p className="text-sm font-bold">Signing evidence</p><p className="mt-1 text-xs leading-5 text-white/55">Keep a dependable history with every agreement.</p></div></div></div></div></section>

    <section id="security" className="bg-[#eef6f2] px-5 py-24 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-[1160px] items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-24"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#0b6b53]">Confidence by default</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">Professional on the outside. Controlled underneath.</h2><p className="mt-5 max-w-lg text-base leading-7 text-[#5b7182]">Give recipients a simple experience while your team keeps the controls and records needed to manage important documents responsibly.</p><Link href="/signup" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#0b6b53]">Create your secure workspace <ArrowRight className="size-4" /></Link></div><div className="grid gap-3 sm:grid-cols-2">{[[ShieldCheck, 'Complete audit history', 'Capture the important events around delivery, access, and completion.'], [LockKeyhole, 'Protected document access', 'Use recipient-specific links and controlled document delivery.'], [Fingerprint, 'Signature evidence', 'Keep signing information together with the final agreement.'], [FileCheck2, 'Central document record', 'Store completed files where your team can find them later.']].map(([Icon, title, copy]) => { const SecurityIcon = Icon as typeof ShieldCheck; return <article key={title as string} className="rounded-2xl border border-[#102a43]/10 bg-white p-6"><SecurityIcon className="size-5 text-[#0b6b53]" /><h3 className="mt-5 text-sm font-bold">{title as string}</h3><p className="mt-2 text-xs leading-5 text-[#65798b]">{copy as string}</p></article>; })}</div></div></section>

    <section className="bg-white px-5 py-20 sm:px-8 sm:py-24"><div className="mx-auto flex max-w-[1160px] flex-col items-start justify-between gap-8 rounded-[24px] bg-[#0b6b53] px-7 py-10 text-white sm:px-12 sm:py-12 lg:flex-row lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#b9e7da]">Ready when you are</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.045em] sm:text-4xl">Send your next agreement with confidence.</h2><p className="mt-3 text-sm text-white/65">Create a workspace and prepare your first document in minutes.</p></div><Link href="/signup" className="inline-flex h-12 shrink-0 items-center gap-2 rounded-lg bg-white px-6 text-sm font-bold text-[#0b6b53] transition hover:-translate-y-0.5">Get started <ArrowRight className="size-4" /></Link></div></section>

    <footer className="bg-[#0b1f30] px-5 text-white sm:px-8"><div className="mx-auto max-w-[1160px] py-14 sm:py-16"><div className="grid gap-12 border-b border-white/10 pb-12 lg:grid-cols-[1.15fr_1.85fr]"><div className="max-w-sm"><Link href="#top" className="flex items-center gap-2.5"><Mark light /><span className="text-xl font-bold tracking-[-0.04em]">signet</span></Link><p className="mt-5 text-sm leading-6 text-white/55">Electronic signatures and agreement workflows for teams that want business to move clearly and securely.</p><a href="mailto:hello@send.frogmentec.ae" className="mt-5 inline-block text-sm font-semibold text-[#8dd7c2]">hello@send.frogmentec.ae</a></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3">{footerGroups.map((group) => <div key={group.title}><p className="text-xs font-bold uppercase tracking-[0.16em] text-white/40">{group.title}</p><div className="mt-5 flex flex-col gap-3">{group.links.map(([label, href]) => <Link key={label} href={href} className="text-sm text-white/65 transition hover:text-white">{label}</Link>)}</div></div>)}</div></div><div className="flex flex-col gap-3 pt-7 text-xs text-white/35 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 Signet. All rights reserved.</p><p>Secure agreements, without the busywork.</p></div></div></footer>
  </main>;
}
